<?php

declare(strict_types=1);

namespace Spora\Plugins\MediaArchive;

use Spora\Apps\VueAppInterface;

/**
 * Admin-panel metadata for the Media Archive. Implementing
 * {@see VueAppInterface} (instead of the plain {@see \Spora\Apps\AppInterface})
 * opts the app into the host SPA's generic `/apps/:appName` loader, which
 * lazy-imports `/plugins/<slug>/<entry>` and mounts the IIFE bundle inside
 * the shared layout.
 *
 * The slug returned by {@see name()} (`media-archive`) is the host SPA's
 * route key. It is independent of the Composer package name (which is
 * `spora-ai/spora-plugin-media-archive`) and of the frontend bundle's
 * on-disk directory (which is derived from the *frontend* package's name
 * by {@see \Spora\Composer\SporaPluginFrontendInstaller}, not this one).
 *
 * The `entry()` value (`main.js`) MUST match the frontend bundle's
 * `build.lib.fileName()` from its `vite.config.ts`. The build pipeline is
 * documented in `spora-plugin-media-archive-frontend/README.md`.
 */
final class MediaArchiveApp implements VueAppInterface
{
    public function name(): string
    {
        return 'media-archive';
    }

    public function displayName(): string
    {
        return 'Media Archive';
    }

    public function description(): string
    {
        return 'Browse, filter, and download media generated by your agents.';
    }

    public function icon(): string
    {
        // `image` is in the bundled icon palette — see
        // spora-core/docs/07_plugins.md § Bundled icons.
        return 'image';
    }

    public function entry(): string
    {
        return 'main.js';
    }
}
