<?php

declare(strict_types=1);

use Spora\Apps\VueAppInterface;
use Spora\Plugins\MediaArchive\MediaArchiveApp;

/**
 * MediaArchiveApp is metadata-only: the SPA consumes it via
 * `GET /api/v1/apps`, which {@see Spora\Http\AppsController} serialises by
 * calling each method. Locking the values here prevents silent route drift
 * (e.g. someone renaming `media-archive` to `media-archive-v2` would break
 * `/apps/media-archive` bookmarks and the Apps dropdown).
 */
it('returns the stable route key', function (): void {
    $app = new MediaArchiveApp();

    expect($app->name())->toBe('media-archive');
});

it('exposes a display name for the navbar', function (): void {
    $app = new MediaArchiveApp();

    expect($app->displayName())->toBe('Media Archive');
});

it('describes what the panel does', function (): void {
    $app = new MediaArchiveApp();

    expect($app->description())
        ->toBe('Browse, filter, and download media generated by your agents.');
});

it('uses the bundled `image` icon', function (): void {
    // `image` is a bundled icon name in spora-core's palette. Switching to
    // a raw SVG path here would be a UX-visible change (different navbar
    // glyph), so we lock the value.
    $app = new MediaArchiveApp();

    expect($app->icon())->toBe('image');
});

it('declares main.js as the Vue IIFE entry', function (): void {
    // MUST match `build.lib.fileName()` in the frontend package's
    // `vite.config.ts`. If you bump one, bump the other.
    $app = new MediaArchiveApp();

    expect($app->entry())->toBe('main.js');
});

it('implements VueAppInterface', function (): void {
    // Belt-and-braces: `instanceof` works through the interface because
    // `VueAppInterface` only declares methods (no state), but checking the
    // class name is the cheapest way to assert the contract.
    expect(MediaArchiveApp::class)
        ->toImplement(VueAppInterface::class);
});
